[base]
workshop = []
parameters = [
    "-window",
    "-noPause",
    "-noPauseAudio",
]

# executable = "arma3_x64"        # Default: "arma3_x64"
# file_patching = true # Default: true
# binarize = false # Default: false
# rapify = true # Default: true

presets = []
dlc = []
optionals = []


[default]
extends = "base"
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    #"463939057",  # ACE3
    "1882627645", # Anrop ACE
    "3499977893", # Advanced Developer Tools
    "1779063631", # ZEN
]
dlc = []

[test]
extends = "default"
mission = "test.VR"

[bw]
extends = "default"
workshop = [
    "1200127537", # BW Mod
]

[3cb]
extends = "default"
workshop = [
    "893328083" # 3CB BAF Equipment
]

[amf]
extends = "default"
workshop = [
    "1781990846", # Arma Mod France
]

# CUP based Presets
[cup]
extends = "default"
workshop = [
    "497660133", # CUP Weapons
    "541888371", # CUP Vehicles
    "497661914", # CUP Units
]

[cfp]
extends = "cup"
workshop = [
    "1369691841", # Community Factions Project
]

[cwr3]
extends = "cup"
workshop = [
    "2316343124", # Cold War Rearmed III
]

[ldf]
extends = "cup"
workshop = [
    "3294585159", # (CUP) Livonian Defense Force
]

[ukr]
extends = "cup"
workshop = [
    "3312210548", # (CUP) Ukrainian Armed Forces
]

[fin]
extends = "cup"
workshop = [
    "3465921651", # (CUP) Finnish Defence Forces
]

[nor]
extends = "cup"
workshop = [
    "3333292879", # (CUP) Norwegian Armed Forces
]

[pol]
extends = "cup"
workshop = [
    "3459905206", # (CUP) Polish Armed Forces
]

# RHS based Presets
[rhs]
extends = "default"
workshop = [
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
]

[po]
extends = "rhs"
workshop = [
    "735566597", # Project OPFOR
]

[3cbf]
extends = "rhs"
workshop = [
    "1673456286", # 3CB Factions Pack
]
